name: ZSAR
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - numpy>=1.19.2
  - pandas>=1.3.0
  - opencv>=4.5.3
  - scikit-learn>=0.24.2
  - tqdm>=4.62.3
  - matplotlib>=3.4.3
  - ftfy
  - regex
  - pip
  - pip:
      - transformers>=4.11.0
      - clip
